### ISSUE TITLE
Do IMU orientation check of the relative orientation w.r.t. the initial pose, instead of w.r.t. to the absolute pose

### ISSUE THREAD

**Issue by traversaro** [ami-iit/xcub-sensors-check#8]
If I understood the code correctly, the orientation check is done by comparing for a dataset with samples from $1$ to $N$ by comparing the following orientations:

* ${{}^{W_{IMU}}} R_S^i \in SO(3)$ : the orientation measured by the IMU ($W_{IMU}$) is the world of the IMU, $S$ the sensor frame of the IMU)
${{}^{W_{FK}}} R_S^i \in SO(3)$ : the orientation measured by the forward kinematics ($W_{FK}$ is the world of the forward kinematics)

however, this is not convenient as in general the $W_{FK}$ and $W_{IMU}$ are different, and even if the $W_{FK}$ can be specified via the `base_link_orientation_rpy_deg` parameter, it is not trivial to align them manually.

Perhaps a possible improvement could be to compare instead the relative orientation of the sensor and the forward kinematics w.r.t. to the initial position, i.e. : 

* ${{}^{W_{IMU}}} {R_S^0}^T {{}^{W_{IMU}}} R_S^i$
* ${{}^{W_{FK}}} {R_S^0}^T {{}^{W_{FK}}} R_S^i$

In this way, we are comparing for both FK and IMU an estimation of the quantity ${}^{S^0} R_{S^i}$, that is automatically consistent.

**Comment by traversaro** [comment]
fyi @GiulioRomualdi @Nicogene @martinaxgloria

**Comment by S-Dafarra** [comment]
I think this is done by aligning the first IMU measurement with the one coming from the FK in https://github.com/ami-iit/xcub-sensors-check/blob/6883366598efc2c301be92314f2fd09921cff54f/xcub_sensor_check/IMU_test.py#L258-L286

**Comment by traversaro** [comment]
I may be missing something, but following the code `I_T_base` is computed only once, and from a parameter, it is never set to another value:
* https://github.com/ami-iit/xcub-sensors-check/blob/6883366598efc2c301be92314f2fd09921cff54f/xcub_sensor_check/IMU_test.py#L248
* https://github.com/ami-iit/xcub-sensors-check/blob/6883366598efc2c301be92314f2fd09921cff54f/xcub_sensor_check/IMU_test.py#L58-L79

**Comment by S-Dafarra** [comment]
> I may be missing something, but following the code `I_T_base` is computed only once, and from a parameter, it is never set to another value:

That is the base transform matrix. The matrix you are looking for is named ``I_R_I_IMU ``

**Comment by traversaro** [comment]
> > I may be missing something, but following the code `I_T_base` is computed only once, and from a parameter, it is never set to another value:
> 
> That is the base transform matrix. The matrix you are looking for is named `I_R_I_IMU `

That is right, I missed the code in https://github.com/ami-iit/xcub-sensors-check/blob/6883366598efc2c301be92314f2fd09921cff54f/xcub_sensor_check/IMU_test.py#L312-L315 , thanks for pointing out. fyi @Nicogene @martinaxgloria 

Closing then as what is described (or something quite similar) is basically already implemented.
